### ISSUE TITLE
Support for Swift 4 and Xcode 9

### ISSUE THREAD

**Issue by jeremiah-bouncechat** [imgly/pesdk-ios-build#1]
I am getting this error when using the Xcode 9 beta:

> Module compiled with Swift 3.1 cannot be imported in Swift 4.0: /.../Pods/imglyKit/pesdk-ios-build-6.5.0/imglyKit.framework/Modules/imglyKit.swiftmodule/x86_64.swiftmodule

**Comment by sascha** [comment]
Hi @jeremiah-bouncechat, we are currently working on a plan on how we will support Swift 4 beta in addition to Swift 3.1. You can expect an update regarding this within the next few days.

**Comment by jeremiah-bouncechat** [comment]
Cool, thanks. According to the docs, you should be able to compile Swift 3 code with the Swift 4 compiler. https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Compatibility.html

**Comment by jeremiah-bouncechat** [comment]
@sascha I see that 7.1.1 supports Xcode 9, but I'm still getting the same error. Any thoughts?

**Comment by sascha** [comment]
@jeremiah-bouncechat Sorry this took a while. A pre-release that should work with Xcode 9 is available here: https://github.com/imgly/pesdk-ios-build/releases/tag/7.2.0-swift.4.0.beta.2
