### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by swells808** [imgly/pesdk-ios-build#10]
Getting this when I do "import PhotoeditorSDK" in Xcode. Are you going to have an updated version soon?

**Comment by sascha** [comment]
Hi @swells808, are you using the latest version of the SDK? Version 8.3.0 and 8.3.1 are built with Swift 4.1.

**Comment by swells808** [comment]
Thanks that was it for some reason loaded 8.2.4!
