### ISSUE TITLE
Is there any way to reduce the size of  SDK  through configuration ?

### ISSUE THREAD

**Issue by Muthukumar123** [imgly/pesdk-ios-build#12]

**Comment by Muthukumar123** [comment]
something like minified version . 80 MB of SDK is too heavy for our application . I have raised the ticket bu there is no response as well .

**Comment by sascha** [comment]
Unfortunately it is currently not possible to get a minified version of the SDK. A detailed description about the framework's size is available here: https://docs.photoeditorsdk.com/guides/ios/v8/resources/faq
