### ISSUE TITLE
The executable for XXX.app/Frameworks/PhotoEditorSDK.framework contains unsupported architectures '[x86_64, i386]'

### ISSUE THREAD

**Issue by davidgv88** [imgly/pesdk-ios-build#13]
Before archive...

<img width="752" alt="captura de pantalla 2018-06-27 a las 14 43 14" src="https://user-images.githubusercontent.com/679262/41974758-1c35d68c-7a19-11e8-9114-6cc1258181fe.png">

Error
<img width="667" alt="captura de pantalla 2018-06-27 a las 14 34 14" src="https://user-images.githubusercontent.com/679262/41974919-94678f24-7a19-11e8-9b32-c358fa9b9cb3.png">

**Comment by sascha** [comment]
Hi @davidgv88, are you sure you followed step 2 of the manual integration guide (https://docs.photoeditorsdk.com/guides/ios/v8/introduction/getting_started#manually)?

**Comment by davidgv88** [comment]
I'm using cordova plugin https://github.com/imgly/pesdk-cordova-demo

i'm going to try!

**Comment by davidgv88** [comment]
Thanks @sascha now works!

Hi @maltebaumann look at this thread. Is posibly add this "Run Script Phase" to the Cordova plugin?

I will create the issue in this repository https://github.com/imgly/pesdk-cordova-demo
