### ISSUE TITLE
photoeditorsdk apply filter to a UIImage for IOS with swift

### ISSUE THREAD

**Issue by VamsiKrishna2112** [imgly/pesdk-ios-build#14]
I have gone through the Android API document of photoeditorsdk and found that I can directly apply a filter on an image using

```
ImageFilter imageFilter = new ColorFilterAD1920();
imageFilter.renderImage(Bitmap bitmap, boolean previewRendering)
```
doing this returns me with an image with the desired filter applied.

How can i achieve the same in IOS

**Comment by sascha** [comment]
Hi @VamsiKrishna2112, please file a report request at https://support.photoeditorsdk.com.
