### ISSUE TITLE
Module compiled with Swift 3.1 cannot be imported in Swift 3.2

### ISSUE THREAD

**Issue by SalvatoreAD** [imgly/pesdk-ios-build#2]
Can You Help me? 
I use 
pod 'PhotoEditorSDK', '~> 7.3'

**Comment by sascha** [comment]
Please use https://github.com/imgly/pesdk-ios-build/releases/tag/7.3.0-swift.4.0 with Xcode 9. Unfortunately this version can't be installed via CocoaPods, so you will have to integrate it manually as described [here](https://docs.photoeditorsdk.com/guides/ios/v7/introduction/getting_started#manually).
