### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2

### ISSUE THREAD

**Issue by aneena-thomas** [imgly/pesdk-ios-build#6]
When i run in Xcode 9.1(Swift 4.0) also it shows ,

Module compiled with Swift 4.0 cannot be imported in Swift 4.0.2: /Users/Aneena/Documents/ImageFilter/pesdk-ios-examples-master/Examples/SwiftExample/Pods/PhotoEditorSDK/pesdk-ios-build-8.1.2/PhotoEditorSDK.framework/Modules/PhotoEditorSDK.swiftmodule/x86_64.swiftmodule

**Comment by sascha** [comment]
Hi @aneena-thomas, which version of the SDK do you use?

**Comment by aneena-thomas** [comment]
I just pod install the PhotoEditorSDK.So don't know the version.

**Comment by sascha** [comment]
@aneena-thomas Then CocoaPods most likely installed the latest available version of the SDK (8.2.4). You can verify that by looking at your Podfile.lock

Version 8.2.4 requires the latest Xcode 9.2. Please update your Xcode and let me know if the issue still occurs.

**Comment by aneena-thomas** [comment]
Already tried Xcode 9.2 still it not working and shows the same error

SDK Version is 8.2.4

**Comment by sascha** [comment]
Would you please try to clean the project or remove the contents of your derived data folder (`rm -rf ~/Library/Developer/Xcode/DerivedData/*`)?

**Comment by aneena-thomas** [comment]
This one also tried

**Comment by aneena-thomas** [comment]
And my sdk version is 8.1.2

**Comment by aneena-thomas** [comment]
![screen shot 2018-02-22 at 4 08 31 pm](https://user-images.githubusercontent.com/13118654/36533658-3e1fdca2-17ea-11e8-9561-c181021db40b.png)

**Comment by sascha** [comment]
Can you update to the latest version? `pod update`

**Comment by aneena-thomas** [comment]
Thanks @sascha its working fine now
