### ISSUE TITLE
Module compiled with Swift 4.0.3 cannot be imported in Swift 4.1

### ISSUE THREAD

**Issue by jasonkruit** [imgly/pesdk-ios-build#7]
Trying to get my app tested against next iOS version. Any chance there is an update coming soon?

**Comment by sascha** [comment]
@jasonkruit Sure, we can release a prerelease for Xcode 9.3 next week. Will let you know when it is available here then.

**Comment by jasonkruit** [comment]
Thank you.

**Comment by sascha** [comment]
https://github.com/imgly/pesdk-ios-build/releases/tag/8.2.4-xcode.9.3.beta.3
