### ISSUE TITLE
No cocoapods release that supports Xcode 9.3

### ISSUE THREAD

**Issue by landonalder** [imgly/pesdk-ios-build#8]
There is currently no cocoapods release (that I can see) that supports Xcode 9.3.

**Comment by menkel** [comment]
👍

**Comment by sascha** [comment]
We just released version 8.3.0 of the iOS SDK, built with Swift 4.1 / Xcode 9.3. More details are available at https://github.com/imgly/pesdk-ios-build/releases/tag/8.3.0

**Comment by landonalder** [comment]
Thank you!

**Comment by menkel** [comment]
Thank you !

**Comment by AliTariqQuantum** [comment]
This is not available via Pod? 

Searching pod for PhotoEditorSDK results this 

```
-> PhotoEditorSDK (8.2.4)
   Integrate the photo editor into your own HTML5, iOS or Android app - in
   minutes!
   pod 'PhotoEditorSDK', '~> 8.2.4'
   - Homepage: https://www.photoeditorsdk.com
   - Source:   https://github.com/imgly/pesdk-ios-build/archive/8.2.4.zip
   - Versions: 8.2.4, 8.2.3, 8.2.2, 8.2.1, 8.2.0, 8.1.3, 8.1.2, 8.1.1, 8.1.0,
   8.0.1, 8.0.0, 7.3.0, 7.2.0, 7.1.1, 7.1.0, 7.0.1, 7.0.0 [master repo]
```

And using `pod 'PhotoEditorSDK', '~> 8.3.1’` results 

```
[!] CocoaPods could not find compatible versions for pod "PhotoEditorSDK":
  In Podfile:
    PhotoEditorSDK (~> 8.3.1)
```

**Comment by sascha** [comment]
It is available (see https://cocoapods.org/pods/PhotoEditorSDK). Did you try running `pod repo update`?

**Comment by AliTariqQuantum** [comment]
`pod repo update` fixed the issue
