### ISSUE TITLE
Unable to Load in XCode 9.2, Objective C via CocoaPods or manually embedding - Crashes on Launch

### ISSUE THREAD

**Issue by aksharbonu** [imgly/pesdk-ios-build#9]
Trying to get the SDK to work in my Objective C project. Using Xcode 9.2 and tried manually / via cocoapods but the app crashes on launch.

**Comment by sascha** [comment]
Please file a support request at http://support.photoeditorsdk.com. Also, please make sure to include the exact error message and/or stack trace and a sample project which reproduces the issue.
